remote_theme: pages-themes/cayman@v0.2.0
plugins: 
- jekyll-remote-theme
title: GizOz
description: Aplikasi GizOz merupakan aplikasi yang dibuat untuk membantu pengguna dalam menentukan makanan yang harus dikonsumsi sesuai dengan informasi diri yang diberikan  dan program yang dipilih.
